# Site settings
title: Bloggium
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/Bloggium" # the subpath of your site, e.g. /blog/
url: "http://rub3jr.github.io/Bloggium" # the base hostname & protocol for your site
twitter_username: ruben_j_rios
github_username:  rub3jr
github_projecturl:  "https://github.com/rub3jr/bloggium/tree/gh-pages/"

# Build settings
markdown: kramdown
# Use the redcarpet Markdown renderer 
#markdown: redcarpet 


#if you wish to integrate disqus on pages set your shortname here 
disqus_shortname: '' 

 
# if you use google analytics, add your tracking id here 
google_analytics_id: 'UA-62515009-1' 


collections:
  docs:
    output: true


